{
  "hoistedDependencies": {},
  "hoistPattern": [
    "*"
  ],
  "included": {
    "dependencies": true,
    "devDependencies": true,
    "optionalDependencies": true
  },
  "layoutVersion": 5,
  "nodeLinker": "isolated",
  "packageManager": "pnpm@12.4.2",
  "pendingBuilds": [],
  "prunedAt": "Fri, 18 Sep 2026 18:51:29 GMT",
  "publicHoistPattern": [],
  "skipped": [],
  "storeDir": "C:\\Users\\mohdk\\AppData\\Local\\pnpm\\store\\v11",
  "virtualStoreDir": "C:\\Users\\mohdk\\Downloads\\something-special\\node_modules\\.pnpm",
  "virtualStoreDirMaxLength": 60,
  "allowBuilds": {}
}